### ISSUE TITLE
Executing Test and Setup method in different 

### ISSUE THREAD

**Issue by nasirodin** [ricaun-io/RevitTest#19]
Can the `Test` and `Setup` methods be executed in separate external events? Running these methods in separate external events may resolve the [issue](https://forums.autodesk.com/t5/revit-api-forum/element-collector-inaccurate-results-when-using/m-p/9944920) with the `UIApplication.OpenAndActivateDocument` method. After activating the document, the `FilteredElementCollector` doesn't function correctly unless the query is executed in a separate external event.

**Comment by ricaun** [comment]
Hey @nasirodin 

Why exactly you need to use `UIApplication.OpenAndActivateDocument`? You really need the `UIDocument`?

I thought to add some way to run each test in a different external events but would be complicated to implement.

There is a experimental feature that make some tests run outside the Addin Context. 

Make some tests to run asynchronous and make possible open a document with `UIApplication.OpenAndActivateDocument` but the setup is not good.

Because all the test run outside the context you need to create your own `ExternalEvent` and Raise yourself, and make sure to wait the `ExternalEvent` to finish.

**Comment by nasirodin** [comment]
Thank you @ricaun 
I'm using UIDocument to work with UIView in one of my use cases. but I think I might be able to refactor my code and find a way around it
